# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
disabled = false
detect_files = ['helmfile.yaml', 'values.yaml']
detect_folders = ['k8', 'k8s']
format = 'on [⛵ ($cluster in ) \($namespace\)](dimmed blue) '